{{- if and .Values.uploads.persistence.enabled (not .Values.uploads.persistence.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wp-boilerplate.fullname" . }}-uploads
  labels:
    {{- include "wp-boilerplate.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.uploads.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.uploads.persistence.size | quote }}
  {{- if .Values.uploads.persistence.storageClass }}
  storageClassName: {{ .Values.uploads.persistence.storageClass | quote }}
  {{- end }}
{{- end }}

