{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wp-boilerplate.serviceAccountName" . }}
  labels:
    {{- include "wp-boilerplate.labels" . | nindent 4 }}
{{- end }}

