apiVersion: v1
kind: Service
metadata:
  name: {{ include "wp-boilerplate.fullname" . }}
  labels:
    {{- include "wp-boilerplate.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "wp-boilerplate.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.metrics.phpFpmExporter.port }}
      targetPort: metrics
    {{- end }}

