<?php

/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 *
 * This file is required in the web/ directory so WordPress can find it:
 * WordPress is hardcoded to look in its own directory or one directory up.
 */
require_once dirname(__DIR__) . '/vendor/autoload.php';
require_once dirname(__DIR__) . '/config/application.php';
require_once ABSPATH . 'wp-settings.php';

